#! /usr/bin/env bash

# If we have an error, bail out!
set -e

# If we're debugging, be really loudly verbose
[[ ! -z $DEBUG ]] && set -x

# This script only works if Maven is installed.. test for it.
if [[ ! -e $(which mvn) ]]; then
  echo 'You must have maven2 and a JDK installed.'
  exit 1
fi

# Attempt to load up the /etc/lsb-release file to determine our OS. If none is
# found, we default our settings to RHEL/Amazon Linux as the original behavior
# of this script intended.
if [[ -f /etc/lsb-release ]]; then
  dist=Ubuntu
elif [[ -f /etc/debian_version ]]; then
  dist=Debian
else
  dist=Redhat
fi

# Tell the user what OS we detected
echo "Detected OS Distro: ${dist}"

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
 echo "This script must be run as root" >&2
 exit 1
fi

# Based on the OS, determine which commands we'll be calling to install/manage
# certain things
case "$dist" in
  Ubuntu)
    init_dir=/etc/init.d
    sysconfig_dir=/etc/default ;;
  Debian)
    init_dir=/etc/init.d
    sysconfig_dir=/etc/default ;;
  *)
    init_dir=/etc/rc.d/init.d
    sysconfig_dir=/etc/sysconfig ;;
esac

daemon_name=aws-kinesis-agent
agent_user_name=aws-kinesis-agent-user
bin_dir=/usr/bin
cron_dir=/etc/cron.d
config_dir=/etc/aws-kinesis
config_flow_dir=${config_dir}/agent.d
jar_dir=/usr/share/${daemon_name}/lib
log_dir=/var/log/${daemon_name}
state_dir=/var/run/${daemon_name}
agent_service=${init_dir}/${daemon_name}

usage() {
  echo "Usage:"
  echo "To install Kinesis Agent, type:"
  echo "  sudo <script-path>/setup --install"
  echo "To uninstall Kinesis Agent, type:"
  echo "  sudo <script-path>/setup --uninstall"
}

fail() {
  echo $1 >&2
  exit 1
}

do_uninstall () {
  echo "Uninstalling $daemon_name ..."
  # stop the service if it's running
  if [ -f $agent_service ]; then
    echo "Stopping $daemon_name..."
    $agent_service stop
  fi

  # remove the service from system services
  echo "Removing $daemon_name from system services..."
  case "$dist" in
    Ubuntu) update-rc.d -f $daemon_name remove > /dev/null 2>&1 || true ;;
    Debian) update-rc.d -f $daemon_name remove > /dev/null 2>&1 || true ;;
    *) chkconfig --del $daemon_name > /dev/null 2>&1 || true ;;
  esac
  
  # remove the jars and config files
  rm -rf ${state_dir}
  rm -rf ${log_dir}
  rm -rf ${jar_dir}
  rm -f ${agent_service}
  rm -f ${bin_dir}/start-${daemon_name}
  
  # remove the user for starting the agent
  userdel $agent_user_name > /dev/null || true
  
  # remove sysconfig
  rm -f ${sysconfig_dir}/${daemon_name}
  
  # remove cron job	
  rm -f ${bin_dir}/${daemon_name}-babysit
  rm -f ${cron_dir}/${daemon_name}

  return 0
}

do_build () {
  mvn -s .m2/conf/settings.xml package -DskipTests || fail "Failed to build the Java project"
}

do_install () {
  do_uninstall

  # Discover the version of the target binary - this is used to know the file
  # name that is going to be produced when the mvn package command runs.
  echo -n 'Discovering package version... '
  JAR_PREFIX=$(mvn -q \
      -Dexec.executable=echo \
      -Dexec.args='${project.artifactId}-${project.version}' \
      --non-recursive \
      exec:exec)
  echo $JAR_PREFIX
  
  echo "Installing Kinesis Agent ${JAR_PREFIX}"

  # Only build if we need to.. but leave the do_build function untouched in
  # case someone wants to force the build.
  test -f ./target/${JAR_PREFIX}-jar-with-dependencies.jar || do_build
  
  install -d ${config_dir}
  install -d ${config_flow_dir}
  install -d ${jar_dir}
  install -d ${init_dir}
  install -d ${cron_dir}
  install -d ${sysconfig_dir}
  install -d ${log_dir}
  install -d ${state_dir}
  install -m644 ./target/${JAR_PREFIX}-jar-with-dependencies.jar ${jar_dir}
  install -m755 ./bin/start-${daemon_name} ${bin_dir}
  install -m755 ./bin/${daemon_name}-babysit ${bin_dir}
  install -m755 ./bin/${daemon_name}.${dist} ${init_dir}/${daemon_name}
  install -m644 ./support/${daemon_name}.cron ${cron_dir}/${daemon_name}
  install -m644 ./support/${daemon_name}.sysconfig ${sysconfig_dir}/${daemon_name}
  install -m644 ./src/main/resources/log4j.xml ${config_dir}

  pushd ${jar_dir} && ln -s ${JAR_PREFIX}-jar-with-dependencies.jar amazon-kinesis-agent.jar && popd

  # add a user for starting the agent
  id -u $agent_user_name > /dev/null 2>&1 || \
  useradd -c "Streaming Data Agent" -r $agent_user_name
  usermod -L $agent_user_name
  
  # change the owner of log files and checkpoint files to the user
  chown -R $agent_user_name $state_dir
  chown -R $agent_user_name $log_dir
  
  config_file=${config_dir}/agent.json
  [[ -f ${config_file} ]] || install -m644 ./configuration/release/${daemon_name}.json ${config_file}
  echo "Configuration file installed at: ${config_file}"
  echo "Configuration details:"
  cat "${config_file}"
  
  case "$dist" in
    Ubuntu) update-rc.d $daemon_name defaults ;;
    Debian) update-rc.d $daemon_name defaults ;;
    *) chkconfig --add $daemon_name ;;
  esac
  
  echo "Amazon Kinesis Agent is installed successfully."
  echo "To start the $daemon_name service, run:"
  echo "  sudo service $daemon_name start"
  echo "To stop the $daemon_name service, run:"
  echo "  sudo service $daemon_name stop"
  echo "To check the status of the $daemon_name service, run:"
  echo "  sudo service $daemon_name status"
  echo ""
  echo "$daemon_name log file will be found at: $log_dir"
  
  echo "To make the agent automatically start at system startup, type:"
  echo "  sudo chkconfig $daemon_name on"
  echo ""
  echo "Your installation has completed!"
}

COMMAND=$1
case "$COMMAND" in
  --build)
    shift
    do_build "$@"
    ;;
  --install)
    shift
    do_install "$@"
    ;;
  --uninstall)
    shift
    do_uninstall "$@"
    echo "Kinesis Agent has been uninstalled"
    ;;
  *)
    usage
    ;;
esac
